name: core
description: The core of Alien for Reddit.
version: 0.1.0

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  elmer:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer

  reddit:
    path: ../reddit

dev_dependencies: