name: alien_core
description: The core functionality of the Alien for Reddit client.
version: 0.1.0
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/alien

publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  muex:
    git:
      url: git://github.com/dcov/muex.git
      ref: nnbd_migration
      path: muex

  hive: 1.6.0-nullsafety.2

  markdown: ^3.0.0

  reddit:
    path: ../reddit

  scraper:
    path: ../scraper

  stash_hive: 2.0.0-nullsafety.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

  build_runner: ^1.11.1

  muex_gen:
    git:
      url: git://github.com/dcov/muex.git
      ref: nnbd_migration
      path: muex_gen
