name: core
description: The core of Alien for Reddit.
version: 0.1.0

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  loux:
    git:
      url: git://github.com/dcov/loux.dart.git
      path: loux

  reddit:
    path: ../reddit

dev_dependencies: