name: scraper
description:
version: 0.2.0
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/alien

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  html: 0.15.0
  http: 0.12.2
  isolate: ^2.0.3

dev_dependencies:
  test: ^1.15.7
