name: alien
description: A Reddit client built with Flutter.
version: 0.1.0
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/alien

environment:
  sdk: '>=2.6.0-dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^1.1.3

  elmer_flutter:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer_flutter
  
  flutter_markdown:
    git:
      url: git://github.com/dcov/flutter_markdown.git
      ref: alien

  hive: ^1.1.1

  markdown: ^2.1.1

  reddit:
    path: ../reddit
  
  scraper:
    path: ../scraper

  webview_flutter: ^0.3.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.7

  mockito: ^4.1.1

  elmer_gen:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer_gen

flutter:
  uses-material-design: true

  fonts:
    - family: AlienIcons
      fonts:
        - asset: fonts/subreddit.ttf
