name: alien
description: A Reddit client built with Flutter.

version: 0.1.0

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  elmer_flutter:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: AlienIcons
      fonts:
        - asset: fonts/subreddit.ttf
