name: alien
description: A Reddit client built with Flutter.
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/alien

version: 0.1.0

dependencies:
  flutter:
    sdk: flutter

  elmer_flutter:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer_flutter

  reddit:
    path: ../reddit

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.7

  elmer_gen:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer_gen

flutter:
  uses-material-design: true

  fonts:
    - family: AlienIcons
      fonts:
        - asset: fonts/subreddit.ttf
