name: alien
description: A Reddit client built with Flutter.
version: 0.1.0
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/alien

environment:
  sdk: '>=2.7.0 <3.0.0'

flutter:
  uses-material-design: true

  fonts:
    - family: AlienIcons
      fonts:
        - asset: fonts/subreddit.ttf

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 2.0.0

  elmer_flutter:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer_flutter
  
  flutter_markdown:
    git:
      url: git://github.com/dcov/flutter_markdown.git
      ref: alien

  hive: ^1.4.1+1

  markdown: ^2.1.3

  path_provider: ^1.6.1

  reddit:
    path: ../reddit
  
  scraper:
    path: ../scraper

  webview_flutter: ^0.3.19+8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0

  mockito: ^4.1.1

  elmer_gen:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer_gen

dependency_overrides:
  analyzer: 0.40.0

