name: alien
description: A Reddit client built with Flutter.
version: 0.1.0+2
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/alien

environment:
  sdk: '>=2.7.0 <3.0.0'

flutter:
  uses-material-design: true

  fonts:
    - family: AlienIcons
      fonts:
        - asset: assets/fonts/subreddit.ttf

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 2.3.3

  mal:
    git:
      url: git://github.com/dcov/mal.git
      path: mal

  mal_flutter:
    git:
      url: git://github.com/dcov/mal.git
      path: mal_flutter
  
  flutter_markdown:
    git:
      url: git://github.com/dcov/flutter_markdown.git
      ref: alien

  hive: ^1.4.4

  markdown: ^2.1.3

  package_info: ^0.4.3

  path_provider: ^1.6.1

  reddit:
    path: ../reddit
  
  scraper:
    path: ../scraper

  stash_hive: 1.0.1

  webview_flutter: ^0.3.19+8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0

  flutter_launcher_icons: ^0.8.1

  mockito: ^4.1.1

  mal_gen:
    git:
      url: git://github.com/dcov/mal.git
      path: mal_gen

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/alien-icon-v0.1.0.png"

