name: alien
description: A Reddit client built with Flutter.
version: 0.1.0
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/alien

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^1.1.1

  elmer_flutter:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer_flutter
  
  flutter_markdown:
    git:
      url: git://github.com/dcov/flutter_markdown.git
      ref: alien

  markdown: ^2.0.3

  reddit:
    path: ../reddit
  
  scraper:
    path: ../scraper

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.7

  elmer_gen:
    git:
      url: git://github.com/dcov/elmer.git
      path: elmer_gen

flutter:
  uses-material-design: true

  fonts:
    - family: AlienIcons
      fonts:
        - asset: fonts/subreddit.ttf
