name: reddit
description: The Reddit API wrapper use in Alien for Reddit. 
version: 0.1.0
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/alien

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  http: ^0.12.0
  uuid: ^2.0.2
  built_value: ^6.7.0

dev_dependencies:
  build_runner: ^1.6.2
  built_value_generator: ^6.7.0
  test: ^1.6.5
